---
title: "Chapter11 List"
output: github_document
---

## 11.1 List

R中列表(list)类型来保存不同类型的数据。 一个主要目的是提供R分析结果输出包装： 输出一个变量， 这个变量包括回归系数、预测值、残差、检验结果等等一系列不能放到规则形状数据结构中的内容。 实际上，数据框也是列表的一种， 但是数据框要求各列等长， 而列表不要求。

列表可以有多个元素， 但是与向量不同的是， 列表的不同元素的类型可以不同， 比如， 一个元素是数值型向量， 一个元素是字符串， 一个元素是标量， 一个元素是另一个列表。

定义列表用函数`list()`, 如

```{r}
rec <- list(name="李明", age=30,
  scores=c(85, 76, 90))
rec
## $name
## [1] "李明"
## 
## $age
## [1] 30
## 
## $scores
## [1] 85 76 90
```

## 11.2 List Indexing

```{r}
rec[[3]]
## [1] 85 76 90
rec[[3]][2]
## [1] 76
rec[["age"]]
## [1] 30
```

```{r}
rec$age
## [1] 30
```

```{r}
rec[3]
## $scores
## [1] 85 76 90
is.list(rec[3])
## [1] TRUE
```

```{r}
names(rec)
## [1] "name"   "age"    "scores"
names(rec)[names(rec)=="scores"] <- "三科分数"
names(rec)
## [1] "name"     "age"      "三科分数"
rec[["三科分数"]]
## [1] 85 76 90
```

```{r}
rec[["三科分数"]][2] <- 0
print(rec)
## $name
## [1] "李明"
## 
## $age
## [1] 30
## 
## $三科分数
## [1] 85  0 90
```

```{r}
rec[["身高"]] <- 178
print(rec)
```

```{r}
rec[["age"]] <- NULL
print(rec)
## $name
## [1] "李明"
## 
## $三科分数
## [1] 85  0 90
## 
## $身高
## [1] 178
```

```{r}
li <- list(a=120, b="F", c=NULL); li
## $a
## [1] 120
## 
## $b
## [1] "F"
## 
## $c
## NULL
```

```{r}
li["b"] <- list(NULL)
li["d"] <- list(NULL)
li
## $a
## [1] 120
## 
## $b
## NULL
## 
## $c
## NULL
## 
## $d
## NULL
```

## 11.3 List Type Conversion

```{r}
li1 <- as.list(1:3)
li1
## [[1]]
## [1] 1
## 
## [[2]]
## [1] 2
## 
## [[3]]
## [1] 3

```

```{r}
li2 <- list(x=1, y=c(2,3))
unlist(li2)
##  x y1 y2 
##  1  2  3
```

## 11.4 List Concatenation

```{r}
li1 <- list(1:2)
li2 <- list(11:12)
li <- c(li1, li2)
li
## [[1]]
## [1] 1 2
## 
## [[2]]
## [1] 11 12
```

```{r}
li <- list()
li <- c(li, list(1:3))
li <- c(li, list(11:13))
li
## [[1]]
## [1] 1 2 3
## 
## [[2]]
## [1] 11 12 13
```

## 11.5 strsplit()

```{r}
x <- c("10, 8, 7", "5, 2, 2", "3, 7, 8", "8, 8, 9")
res <- strsplit(x, ","); res
## [[1]]
## [1] "10" " 8" " 7"
## 
## [[2]]
## [1] "5"  " 2" " 2"
## 
## [[3]]
## [1] "3"  " 7" " 8"
## 
## [[4]]
## [1] "8"  " 8" " 9"
```

```{r}
t(sapply(res, as.numeric))
##      [,1] [,2] [,3]
## [1,]   10    8    7
## [2,]    5    2    2
## [3,]    3    7    8
## [4,]    8    8    9
```
