---
title: "Chapter12 Matrix"
output: github_document
---

## 12.1 Matrix

```{r}
A <- matrix(11:16, nrow=3, ncol=2); print(A)
```

```{r}
B <- matrix(c(1,-1, 1,1), nrow=2, ncol=2, byrow=TRUE) 
print(B)
B <- matrix(c(1,-1, 1,1), nrow=2, ncol=2, byrow=FALSE) 
print(B)
```

```{r}
nrow(A)
ncol(A)
```

```{r}
class(A)
attributes(A)
dim(A)
```

## 12.2 Subset of Matrix

```{r}
A
cat(A[1,],"A[1,] class: ",class(A[1,]),"\n")
cat(A[,1],"A[,1] class: ",class(A[,1]),"\n")
cat(A[c(1,3), 1:2],"A[c(1,3), 1:2] class: ",class(A[c(1,3), 1:2]),"\n")
```

```{r}
colnames(A) <- c('X', 'Y')
rownames(A) <- c('a', 'b', 'c')
A
```

```{r}
A[,1,drop=FALSE]
```

```{r}
A[A[,1]>=12,'Y']
```

```{r}
c(A)
```

```{r}
diag(2)
```

## 12.3 cbind() and rbind()

```{r}
cbind(c(1,2), c(3,4), c(5,6))
```

```{r}
cbind(A, c(1,-1,10))
```

```{r}
cbind(1, c(1,-1,10))
```

## 12.4 Matrix Computations

```{r}
A
C1 <- A + 2; C1
```

```{r}
C2 <- A / 2; C2
```

```{r}
C1 + C2
```

```{r}
C1 - C2
```

```{r}
C1 * C2
C1 / C2
```

```{r}
A
B
C3 <- A %*% B; C3
```

```{r}
c(1,1) %*% B
```

```{r}
B %*% c(1,1)
```

```{r}
c(1,1) %*% B %*% c(1,1)
```

```{r}
c(1,2,3) %o% c(1, -1)
```

## 12.5 Inverse Matrix

```{r}
solve(B)
```

```{r}
solve(B, c(1,2))
```

## 12.6 apply()

```{r}
D <- matrix(c(6,2,3,5,4,1), nrow=3, ncol=2); D
```

```{r}
apply(D, 2, sum)
```

```{r}
apply(D, 1, mean)
```

```{r}
apply(D, 2, range)
```

```{r}
apply(D, 1, range)
t(apply(D, 1, range))
```

## 12.7 Multidimensional Array

```{r}
ara <- array(1:24, dim=c(2,3,4)); ara
```

```{r}
ara[,,2]
```

```{r}
ara[,2,2:3]
```

## 12.8 List Style Matrix

```{r}
L <- matrix(list(), nrow=2, ncol=2); L
```

```{r}
L[1,1] <- list(1:2)
L[1,2] <- list(3:5)
L[2,1] <- list(6:10)
L[2,2] <- list(11:15)
L
```

```{r}
L[2,2]
```

```{r}
L[2,2][[1]]
```
