---
title: "Chapter13 Dataframe"
output: github_document
---

## 13.1 Dataframe

```{r}
d <- data.frame(
    name=c("李明", "张聪", "王建"), 
    age=c(30, 35, 28), 
    height=c(180, 162, 175),
    stringsAsFactors=FALSE)
print(d)
```

```{r}
names(d)
## [1] "name"   "age"    "height"
colnames(d)
## [1] "name"   "age"    "height"
```

```{r}
knitr::kable(d)
```

```{r}
d[2,3]
## [1] 162
```

```{r}
d[[2]]
## [1] 30 35 28
```

```{r}
d[,2]
## [1] 30 35 28
```

```{r}
d[["age"]]
## [1] 30 35 28
d[,"age"]
## [1] 30 35 28
d$age
## [1] 30 35 28
```

```{r}
x <- d[2,]; x
##   name age height
## 2 张聪  35    162
is.data.frame(x)
## [1] TRUE
```

```{r}
d[1:2, "age"]
## [1] 30 35
d[1:2, c("age", "height")]
##   age height
## 1  30    180
## 2  35    162
d[d[,"age"]>=30,]
##   name age height
## 1 李明  30    180
## 2 张聪  35    162
```

```{r}
rownames(d) <- d$name
d$name <- NULL
d
##      age height
## 李明  30    180
## 张聪  35    162
## 王建  28    175
```

```{r}
dm <- data.frame(
  "年级"=1:6,
  "出游"=c(0, 2, 2, 2, 2, 1),
  "疫苗"=c(TRUE, FALSE, FALSE, FALSE, TRUE, FALSE)
)
dm
```

```{r}
rownames(dm) <- dm[["年级"]]
dm[["年级"]] <- NULL
dm
```

```{r}
ind <- c(2,1,1,3)
dm[as.character(ind),]
##     出游  疫苗
## 2      2 FALSE
## 1      0  TRUE
## 1.1    0  TRUE
## 3      2 FALSE
```

```{r}
ind <- c(2,1,1,3)
xx <- dm[as.character(ind),]
rownames(xx) <- NULL
xx
```

## 13.2 tibble Dataframe

```{r}
library(tibble)
library(readr)
d.class <- read_csv("data/class.csv")
head(d.class)
```

```{r}
class(d.class)
## [1] "spec_tbl_df" "tbl_df"      "tbl"         "data.frame"
```

```{r}
d.bp <- tibble(
  `序号`=c(1,5,6,9,10,15),
  `收缩压`=c(145, 110, "未测", 150, "拒绝", 115)) 
knitr::kable(d.bp)
```

```{r}
tribble(
~`序号`,~`收缩压`,
1,145,
5,110,
6,NA,
9,150,
10,NA,
15,115
) |> knitr::kable()
```

```{r}
readr::read_csv("序号,收缩压
1,145
5,110
6,NA
9,150
10,NA
15,115
") |> knitr::kable()
```

```{r}
d.bp[,"收缩压"]
```

```{r}
d.bp[["收缩压"]]
## [1] "145"  "110"  "未测" "150"  "拒绝" "115"
```

Practice

```{r}
d.class[d.class$age>=15,]
```

```{r}
d.class[d.class$age>=15&d.class$sex=="F",c("age","name")]
```

```{r}
x<-d.class[["age"]]
x<-d.class$age
x
```
