---
title: "Chapter4 Numeric Variables"
output: github_document
---

## 4.1 Numerical Vectors

```{r}
marks <- c(10, 6, 4, 7, 8)
x <- c(1:3, 10:13)
x1 <- c(1, 2)
x2 <- c(3, 4)
x <- c(x1, x2)
x
```

## 4.2 Vectors Computation

```{r}
1.5 + 2.3 - 0.6 + 2.1*1.2 - 1.5/0.5 + 2^3
```

```{r}
## %/% integer division
## %% modulo

5 %/% 3
## [1] 1
5 %% 3
## [1] 2
5.1 %/% 2.5
## [1] 2
5.1 %% 2.5
## [1] 0.1
```

```{r}
x <- c(1, 10)
x + 2
## [1]  3 12
x - 2
## [1] -1  8
x * 2
## [1]  2 20
x / 2
## [1] 0.5 5.0
x ^ 2
## [1]   1 100
2 / x
## [1] 2.0 0.2
2 ^ x
## [1]    2 1024
```

```{r}
c(1, NA, 3) + 10
## [1] 11 NA 13
```

## 4.3 Vector Functions

```{r}
x <- c(33, 55, 11)
sort(x)
## [1] 11 33 55
rev(sort(x))
## [1] 55 33 11
order(x)
## [1] 3 1 2
x[order(x)]
## [1] 11 33 55
```

```{r}
cumsum(1:5)
## [1]  1  3  6 10 15
cumprod(1:5)
## [1]   1   2   6  24 120
```

```{r}
## function seq()
seq(5)
seq(2,5)
seq(5,11,by=2)
seq(5,11,length.out=100)
```

```{r}
rep(c(1,3), 2)
```

```{r}
rep(c(1,3), c(2,4))
```

```{r}
rep(c(1,3), each=2)
```

## 4.4 Complex Vectors

```{r}
complex(real = c(1,0,-1,0), imaginary = c(0,1,0,-1))
```

```{r}
sqrt(-1 + 0i)
## [1] 0+1i
```

## 4.5 Practice

```{r}
# q1
print(sqrt(1:100))
print((1:100)^(1/3))
```

```{r}
#q2
x<- c(77,60,91,73,85,82,35,100,66,75)
sort(x)
order(x)
summary(x)
sd(x)
```

```{r}
#q3
y<-seq(0,1,length.out=100)
y
```
