---
title: "Chapter6 String Variables"
output: github_document
---

## 6.1 String Vectors

```{r}
s1 <- c('abc', '', 'a cat', NA, '李明')
s1
```

## 6.2 Escape Characters and Original Characters

```{r}
cat("\"\n")
```

```{r}
cat(r"(C:\disk\course\math\nFinished!\n)")
```

## 6.3 Paste Function

```{r}
paste(c("ab", "cd"), c("ef", "gh"))
```

```{r}
paste("x", 1:3, sep="")
```

```{r}
paste(c("a", "b", "c"), collapse="")
```

## 6.4 toupper() and tolower()

## 6.5 String Length

```{r}
nchar("wjew23", type='bytes')
```

## 6.6 Substring

```{r}
substr('JAN07', 1, 3)
## [1] "JAN"
```

```{r}
substr(c('JAN07', 'MAR66'), 1, 3)
## [1] "JAN" "MAR"
```

## 6.7 Typecasting

```{r}
substr('JAN07', 4, 5)
## [1] "07"
as.numeric(substr('JAN07', 4, 5)) + 2000
## [1] 2007
as.numeric(substr(c('JAN07', 'MAR66'), 4, 5))
## [1]  7 66
```

```{r}
as.character((1:5)*5)
## [1] "5"  "10" "15" "20" "25"
```

```{r}
sprintf('file%03d.txt', c(1, 99, 100))
```

## 6.8 String Replacing

```{r}
x <- '1, 3; 5'
gsub(';', ',', x, fixed=TRUE)
## [1] "1, 3, 5"
```
